### PR TITLE
debugger support

### PR DESCRIPTION
**Pull request by CzBuCHi**
upgraded version of PR #163

note: precommit hook shows me error in package.json file event when that file is valid - "commented" it out ...

### CODE REVIEW

**Comment by orta** [comment]
Rockin' - any ideas what's going on with the red tests?

**Comment by CzBuCHi** [comment]
iwe hoped u would know :( - tried rename CodeLens and CodeLensProvider ... jestext.test uses mocks - isnt my provider missing in mocks?

**Comment by orta** [comment]
I've sent a PR fixing the tests: https://github.com/CzBuCHi/vscode-jest/pull/1

**Comment by CzBuCHi** [comment]
@orta  yea i sah it yesterday, but didnt get time to actually test it ... will bet back to it this weekend (i hope)

**Comment by orta** [comment]
No worries, just didn't want to have you not following your repo and miss it (happened to me before 👍 )

**Comment by CzBuCHi** [comment]
travis is angry again ... but i dont think, that is my fault - 'disk quota exceeded' :(

**Comment by orta** [comment]
A re-run fixed that, alright, let's get this in and sorted 👍

**Comment by CzBuCHi** [comment]
https://youtu.be/hEtCEcuxprI?t=11s 👍

**Comment by orta** [comment]
This is shipped in 2.5.0

**Pull request merged**
