### PR TITLE
linking jest-editor-support

### PR DESCRIPTION
**Pull request by bookman25**
Opening this for discussion.  I think it's close, minus the fact that we need a new release of jest for the `jest-editor-support` package to be used.

### CODE REVIEW

**Comment by orta** [comment]
amazing - much simpler than my version of this so far 👍

**Comment by bookman25** [comment]
Any idea if/when jest is going to cut a new version so we can use the changes?

**Comment by orta** [comment]
Ah yeah, should have talked to @cpojer about that earlier, I think a Jest release is coming pretty soon. I was testing it out by using `npm link` earlier over the weekend

**Comment by cpojer** [comment]
We'll publish version 18 likely this week if everything goes smoothly :)

**Comment by orta** [comment]
BTW @bookman25 we talk a bit in the reactiflux Jest chat room, you're welcome to pop in for questions there too

**Comment by orta** [comment]
Alright - this is good, and I'm going to try and get this landed tomorrow and figure a process that allows us to use master jest-editor-support inside vscode-jest 👍

**Comment by bookman25** [comment]
I think I've got it working (maybe).  Looks like it has a requirement of Jest 18 now because of the outputFile parameter update.  But just tested this in my local TS project and it appears to be working.  Would be good to very on someone else's machine though :)

**Comment by orta** [comment]
Alright - this looks good, given it a run locally 👍

**Comment by orta** [comment]
time to update the "how to work on this" docs - thanks @bookman25

**Pull request merged**
