### PR TITLE
Adds support for `it.only` expressions.

### LINKED ISSUE #29: it.only is not found and registered as a test case
before
screen shot 2016-12-01 at 08 54 15
after
screen shot 2016-12-01 at 08 54 19

### PR DESCRIPTION
**Pull request by mute**
Fixes #29.

### CODE REVIEW

**Comment by orta** [comment]
Thanks! This is really useful :D

alas, I have some bad news though, this code has moved into Jest [here](https://github.com/facebook/jest/tree/master/packages/jest-editor-support) - I am planning on migrating this repo to the new code today hopefully - so this PR  will need to Jest I'm afraid

**Comment by bookman25** [comment]
https://github.com/facebook/jest/pull/2289

**Comment by orta** [comment]
nice one - thanks @bookman25

**Comment by orta** [comment]
@bookman25 I'm going to add you as an repo collaborator, no extra pressure or anything - but I don't want you to feel blocked if you need to do something

**Comment by orta** [comment]
and thanks @mute

**Pull request closed without merging**
